VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
SHELL=/bin/zsh
_=/usr/bin/make
VSCODE_INJECTION=1
__CFBundleIdentifier=com.microsoft.VSCode
INFOPATH=/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:/opt/homebrew/share/info:
PATH=/opt/homebrew/bin:/opt/homebrew/sbin:/Users/pedromota/.pyenv/shims:/opt/homebrew/opt/python@3.9/libexec/bin:/opt/homebrew/opt/python@3.9/libexec/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/homebrew/bin:/opt/homebrew/sbin:/opt/homebrew/opt/python@3.9/libexec/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/local/bin:/opt/local/sbin:/Users/pedromota/.fzf/bin
LSCOLORS=Gxfxcxdxbxegedabagacad
ZDOTDIR=/Users/pedromota
PYENV_ROOT=/Users/pedromota/.pyenv
LS_COLORS=di
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.nUvStQNNLU/Listeners
PWD=/Users/pedromota/Desktop/42Projects/Minishell
HOMEBREW_CELLAR=/opt/homebrew/Cellar
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MANPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man:/Library/Developer/CommandLineTools/Toolchains/XcodeDefault.xctoolchain/usr/share/man:/opt/homebrew/share/man:/opt/local/share/man:/opt/homebrew/share/man:/usr/share/man:/usr/local/share/man:/opt/homebrew/share/man:/opt/local/share/man:::
PYENV_SHELL=zsh
HOME=/Users/pedromota
LOGNAME=pedromota
ZSH=/Users/pedromota/.oh-my-zsh
VSCODE_GIT_IPC_HANDLE=/var/folders/r0/fz6vtk952_q6pdd8kp527xr40000gn/T/vscode-git-edfad059cd.sock
XPC_FLAGS=0x0
COLORTERM=truecolor
SHLVL=1
USER=pedromota
OLDPWD=/Users/pedromota/Desktop/42Projects/Minishell
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
TERM_PROGRAM=vscode
TMPDIR=/var/folders/r0/fz6vtk952_q6pdd8kp527xr40000gn/T/
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
MallocNanoZone=0
MAKEFLAGS=(null)
MFLAGS=(null)
TERM_PROGRAM_VERSION=1.84.0
XPC_SERVICE_NAME=0
HOMEBREW_PREFIX=/opt/homebrew
HOMEBREW_REPOSITORY=/opt/homebrew
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2
COMMAND_MODE=unix2003
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
USER_ZDOTDIR=/Users/pedromota
PAGER=less
LANG=en_US.UTF-8
MAKELEVEL=1
